modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]]
modId="cmultimeter"
version="${file.jarVersion}"
displayName="Create: Multimeter"
authors="Falcon"
description='''
YIPPEE WASSUP THIS HURTS MY HEAD LMAO
'''
[[dependencies.cmultimeter]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cmultimeter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cmultimeter]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,)"
ordering="AFTER"
side="BOTH"